### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/nanocomponent#11]
Too much stuff is failing, we need to make sure this lib works as intended

**Comment by joshgillies** [comment]
@yoshuawuyts do you need a hand with this? I'm trying to get my head around how to fit `nanocomponent`s into our workflow, so knowing the interface is sound would be of great benefit. 👍

**Comment by yoshuawuyts** [comment]
@joshgillies oh man, having help writing tests would be amazing! - I agree this is critical; it's bitten us on Dat Desktop too (hence the super ad-hoc patches).

For tests I was thinking a combination of [tape](https://github.com/substack/tape) for Node testing and [tape-run](https://github.com/juliangruber/tape-run) for browser testing. Think testing both would be most resilient b/c choo apps tend to be used in both scenarios - reckon that'd work for ya? :sparkles:

**Comment by joshgillies** [comment]
Hey, haven't forgot about this. As you can tell I've been kicking the tires here a bit over the last few weeks. I think the above approach to testing is sound. Lets aim to run up a branch + PR and iterate on tests there! 🎉

**Comment by yoshuawuyts** [comment]
Yeah sounds good!

**Comment by yoshuawuyts** [comment]
Welll, the example mostly covers it - given we have so few lines of code I think bugs are hard to sneak in. Closing C:
