### ISSUE TITLE
should onload and onunload have access to render args?

### ISSUE THREAD

**Issue by ahdinosaur** [yoshuawuyts/nanocomponent#12]
hey @yoshuawuyts, sweet module!

thinking about using this, but then i tried to apply this to a common pattern.

before using `nanocomponent`:

```js
module.exports = function render (model, dispatch) {
  return html`
    <ul onload=${handleLoad}>
      ${model.cats.map(cat => html`
        <li>${cat.name}</li>
      `)}
    </ul>
  `

  function handleLoad (el) {
    dispatch(loadCats())
  }
}
```

while using `nanocomponent`:

```js
module.exports = nanocomponent({
  render: function render (model, dispatch) {
    return html`
      <ul>
        ${model.cats.map(cat => html`
          <li>${cat.name}</li>
        `)}
      </ul>
    `
  },

  onload: function handleLoad (el) {
    // HALP, i don't have a way to dispatch actions!
    dispatch(loadCats())
  }
})
```

or am i missing something? how do you implement this pattern in your code?

**Comment by yoshuawuyts** [comment]
Create a closure + temp var thats set to the dispatcher. I'd generally
never export directly, but always export a closure. Another approach could
be to emit actual DOM events and having your consumer hook into those - not
sure if it's better tho. Hope this kinda helps

**Comment by ahdinosaur** [comment]
hm interesting, okay. thanks for your quick and thoughtful response!
