### ISSUE TITLE
`isMounted` check breaks iteration

### ISSUE THREAD

**Issue by joshgillies** [yoshuawuyts/nanocomponent#16]
This issue may apply more broadly to the way `nanocomponent` manages component instances.

However, in the below example the resulting list contains one item, as opposed to the expected three:

```js
const component = require('nanocomponent')
const html = require('bel')

const li = component({
  render: function (item, index) {
    return html`
    <li>${item}</li>
    `
  }
})

const ol = component({
  render: function (items) {
    return html`
    <ol>
      ${items.map(function (item, index) {
        return li(item, index)
      })}
    </ol>
    `
  }
})

const state = {
  items: ['one', 'two', 'three']
}

function mainView (state) {
  const { items } = state
  return html`
    <section>
      ${ol(items)}
    </section>
  `
}

document.body.appendChild(mainView(state))
```

My hunch here is that the [`isMounted` check](https://github.com/yoshuawuyts/nanocomponent/blob/master/index.js#L124), is causing the issue.

**Comment by joshgillies** [comment]
A very hacky workaround is to do something like:

```js
const _component = require('nanocomponent')

function component (opts) {
  return function () {
    const args = Array.prototype.slice.call(arguments)
    return _component(opts).apply(null, args)
  }
}
```

which introduces numerous other issues, and is totally not recommended as a long term solution to the issue at hand. 😜

**Comment by yoshuawuyts** [comment]
nanocomponent `v3.0.0` is out - don't think this issue is relevant anymore. Also released https://github.com/yoshuawuyts/microcomponent for a more high level take on the API of  nanocomponent
