### ISSUE TITLE
disappearing list

### ISSUE THREAD

**Issue by forresto** [yoshuawuyts/nanocomponent#5]
Not sure if this is choo, nanocomponent, or [nanocomponent-adapters readme](https://github.com/yoshuawuyts/nanocomponent-adapters/#choo) issue. Or an issue with how I'm using those.

Clicking on a list item selects it as expected, but if you click an already-selected item, the list disappears, replaced with `<div></div>`. This is the case that I would expect the `ol(items, selectedIndex, send)` to recycle the cached element, b/c the arguments don't change.

RequireBin-able:
``` js
const component = require('nanocomponent')
const html = require('choo/html')
const choo = require('choo')

const li = component({
  render: function (item, index, selectedIndex, send) {
    function onClick () {
      send('select', index)
    }
    return html`
    <li onclick=${onClick}>
      ${item}
      ${index === selectedIndex ? '<-' : ''}
    </li>
    `
  }
})

const ol = component({
  render: function (items, selectedIndex, send) {
    return html`
    <ol>
      ${items.map(function (item, index) {
        return li(item, index, selectedIndex, send)
      })}
    </ol>
    `
  }
})

const app = choo()

app.model({
  state: {
    items: ['one', 'two', 'three', 'four'],
    selectedIndex: 0
  },
  reducers: {
    select: function (state, data) {
      return {selectedIndex: data}
    }
  },
})

app.router({default: '/'}, ['/', mainView])
document.body.appendChild(app.start())

function mainView (state, prev, send) {
  const {items, selectedIndex} = state
  return html`
    <section>
      ${ol(items, selectedIndex, send)}
    </section>
  `
}
```

**Comment by yoshuawuyts** [comment]
dang, sounds as if the `.isSameNode()` call is being messed up; suspecting it's `morphdom` somehow

**Comment by yoshuawuyts** [comment]
nanocomponent `v3.0.0` is out - don't think this issue is relevant anymore. Also released https://github.com/yoshuawuyts/microcomponent for a more high level take on the API of  nanocomponent
