### ISSUE TITLE
Render [question]

### ISSUE THREAD

**Issue by alterx** [yoshuawuyts/nanocomponent#9]
I'm creating a couple of adapters (for Custom Element API v2 and Angular (2+)) and while looking at the code of `nanocomponent` I could only find one place in which render is called:

```
if (!isRendered) {
      isRendered = true
      args = _args
      element = render.apply(render, args)
      onload(element, handleLoad, handleUnload)
}
```
Once this happens, it seems like it's impossible to re render the component.
Does this mean that the only way to re-render is to actually remove the node and create a new one?
In that case, why do we need the onupdate callback? It looks like there's no way to re-render the component with the updated values (if there is, I'd like to know, maybe I just missed it :D)

Of course we could just do:

```
onupdate: function (el, args) {
    console.log(`totally updating now`);
    this.apply(this, [args]);
},
```
since we call update with `render` as the first parameter of the apply fn. But it wouldn't really help since we can't do anything with the returned node.

I guess my question is, is there a way to re-render the same instance with the updated values, other than re creating the component?

**Comment by yoshuawuyts** [comment]
Yeah, keep a reference to the rendered element inside the closure and use
onupdate to modify its values

**Comment by alterx** [comment]
Interesting, yeah. Tried something like this: 

```
const widgetElement = component({
  onload: function (el) {
    console.log('totally loaded now');
  },
  onunload: function (el) {
    console.log('no more free lunch');
  },
  onupdate: function (el, args) {
    console.log(`totally updating now`);
    el = this.apply(this, [args]);
  },
  render: function (state) {
    return html`
      <p>${state.title}</p>
    `;
  }
});
```
Update gets triggered with a new title, so that's cool but I get the proxied empty div. I know that I could just update the textNode or appendChild but it just feels like it'd be more natural if you could call render with new args and get the instance updated.

Right now, it's just one node but think about bigger, more complex elements. Is still the textNode approach feasible?

**Comment by yoshuawuyts** [comment]
you should never do this.apply - instead take the el returned by onupdate
and modify its content. You can use whatever you like for that, but
personally I prefer morphdom / nanomorph

**Comment by alterx** [comment]
Yeah, it's not a good idea, just wanted to illustrate there's __a__ way to call render (no __the__ right way, tho)
So the suggested way is to modify the element. Perfect, just wanted to have a clear idea of that :) 

Closing this one.
